<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Owner-editable website content
    |--------------------------------------------------------------------------
    |
    | Put replacement files in public/content/* and update these paths when
    | adding or changing homepage media, eBooks, reports, forms, and branches.
    |
    */

    'hero' => [
        'logo' => 'content/hero/sakofah-hero-logo.png',
        'slides' => [
            ['src' => 'content/hero/Hero (1).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (2).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (3).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (4).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (5).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (6).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (7).png', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (8).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (9).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (10).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (11).jpg', 'title' => 'recap'],
            ['src' => 'content/hero/Hero (12).jpg', 'title' => 'recap'],
        ],
    ],

    'promotions' => [
        [
            'id' => 1,
            'slide_image' => 'content/banners/69-01-36.jpg',
            'modal_type' => 'image',
            'modal_content' => 'content/banners/69-01-31.jpg',
        ],
        [
            'id' => 2,
            'slide_image' => 'content/banners/69-01-33.jpg',
            'modal_type' => null,
            'modal_content' => null,
        ],
        [
            'id' => 3,
            'slide_image' => 'content/banners/69-01-34.jpg',
            'modal_type' => null,
            'modal_content' => null,
        ],
        [
            'id' => 4,
            'slide_image' => 'content/banners/69-01-35.jpg',
            'modal_type' => null,
            'modal_content' => null,
        ],
        [
            'id' => 5,
            'slide_image' => 'content/banners/521-2.jpg',
            'modal_type' => null,
            'modal_content' => null,
        ],
        [
            'id' => 6,
            'slide_image' => 'content/banners/345-1.jpg',
            'modal_type' => 'image',
            'modal_content' => 'content/banners/345.jpg',
        ],
    ],

    'ebooks' => [
        [
            'id' => 'annual-report-2560',
            'themeColor' => '#0f766e',
            'foilColor' => '#5eead4',
            'title' => 'รายงานกิจการ 2560',
            'author' => 'SAKOFAH',
            'year' => '2560',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2560 จำนวน 64 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/yymx/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/yymx/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2560-yymx.jpg',
            'edge' => '#e7f4ee',
            'backBg' => '#043c32',
            'backInk' => '255,255,255',
            'spineBg' => '#006747',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2561',
            'themeColor' => '#166534',
            'foilColor' => '#86efac',
            'title' => 'รายงานกิจการ 2561',
            'author' => 'SAKOFAH',
            'year' => '2561',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2561 จำนวน 63 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/tfus/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/tfus/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2561-tfus.jpg',
            'edge' => '#eef8f3',
            'backBg' => '#07513f',
            'backInk' => '255,255,255',
            'spineBg' => '#0f7a55',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2562',
            'themeColor' => '#365314',
            'foilColor' => '#bef264',
            'title' => 'รายงานกิจการ 2562',
            'author' => 'SAKOFAH',
            'year' => '2562',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2562 จำนวน 70 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/kvci/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/kvci/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2562-kvci.jpg',
            'edge' => '#f3f8f5',
            'backBg' => '#082f27',
            'backInk' => '255,255,255',
            'spineBg' => '#00543d',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2563',
            'themeColor' => '#854d0e',
            'foilColor' => '#fde047',
            'title' => 'รายงานกิจการ 2563',
            'author' => 'SAKOFAH',
            'year' => '2563',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2563 จำนวน 109 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/jhna/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/jhna/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2563-jhna.jpg',
            'edge' => '#edf7f2',
            'backBg' => '#0b4639',
            'backInk' => '255,255,255',
            'spineBg' => '#08724f',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2564',
            'themeColor' => '#9a3412',
            'foilColor' => '#fdba74',
            'title' => 'รายงานกิจการ 2564',
            'author' => 'SAKOFAH',
            'year' => '2564',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2564 จำนวน 177 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/oqgx/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/oqgx/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2564-oqgx.jpg',
            'edge' => '#edf7f2',
            'backBg' => '#043c32',
            'backInk' => '255,255,255',
            'spineBg' => '#006747',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2565',
            'themeColor' => '#9f1239',
            'foilColor' => '#fda4af',
            'title' => 'รายงานกิจการ 2565',
            'author' => 'SAKOFAH',
            'year' => '2565',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2565 จำนวน 138 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/wqhv/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/wqhv/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2565-wqhv.jpg',
            'edge' => '#f0faf4',
            'backBg' => '#064e3b',
            'backInk' => '255,255,255',
            'spineBg' => '#047857',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2566',
            'themeColor' => '#6b21a8',
            'foilColor' => '#d8b4fe',
            'title' => 'รายงานกิจการ 2566',
            'author' => 'SAKOFAH',
            'year' => '2566',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2566 จำนวน 110 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/wdsf/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/wdsf/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2566-wdsf.jpg',
            'edge' => '#f3f8f5',
            'backBg' => '#07513f',
            'backInk' => '255,255,255',
            'spineBg' => '#0f7a55',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2567',
            'themeColor' => '#1d4ed8',
            'foilColor' => '#93c5fd',
            'title' => 'รายงานกิจการ 2567',
            'author' => 'SAKOFAH',
            'year' => '2567',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2567 จำนวน 125 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/yykw/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/yykw/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2567-yykw.jpg',
            'edge' => '#eef8f3',
            'backBg' => '#082f27',
            'backInk' => '255,255,255',
            'spineBg' => '#006747',
            'spineInk' => '#ffffff',
        ],
        [
            'id' => 'annual-report-2568',
            'themeColor' => '#0f4c5c',
            'foilColor' => '#67e8f9',
            'title' => 'รายงานกิจการ 2568',
            'author' => 'SAKOFAH',
            'year' => '2568',
            'stars' => 5,
            'desc' => 'รายงานกิจการประจำปี 2568 จำนวน 110 หน้า',
            'href' => 'https://online.anyflip.com/haqcj/kmre/',
            'downloadUrl' => 'https://online.anyflip.com/haqcj/kmre/mobile/index.html',
            'cover' => 'content/ebooks/annual-report-2568-kmre.jpg',
            'edge' => '#e7f4ee',
            'backBg' => '#043c32',
            'backInk' => '255,255,255',
            'spineBg' => '#00543d',
            'spineInk' => '#ffffff',
        ],
    ],

    'downloads' => [
        'reports' => [
            ['year' => '2563', 'name' => 'รายงานกิจการ 2563 (ฉบับสมบูรณ์)', 'path' => 'content/reports/รายงานกิจการ_2563_(สมบูรณ์_online2).pdf'],
            ['year' => '2562', 'name' => 'รายงานกิจการ 2562', 'path' => 'content/reports/รายงานกิจการ_2562.pdf'],
            ['year' => '2561', 'name' => 'รายงานกิจการ 2561', 'path' => 'content/reports/รายงานกิจการ_2561.pdf'],
            ['year' => '2560', 'name' => 'รายงานกิจการ 2560', 'path' => 'content/reports/รายงานกิจการ_2560.pdf'],
            ['year' => '2559', 'name' => 'รายงานกิจการ 2559', 'path' => 'content/reports/รายงานกิจการ_2559.pdf'],
            ['year' => '2558', 'name' => 'รายงานกิจการ 2558', 'path' => 'content/reports/รายงานกิจการ_2558.pdf'],
            ['year' => '2557', 'name' => 'รายงานกิจการ 2557', 'path' => 'content/reports/รายงานกิจการ_2557.pdf'],
        ],
        'forms' => [
            ['name' => 'ใบคำขอสมัครสมาชิก', 'path' => 'content/forms/ใบคำขอสมัครสมาชิก INFORM 68-001.pdf'],
            ['name' => 'แบบฟอร์มคำขอรับสวัสดิการ', 'path' => 'content/forms/คำขอรับสวัสดิการสมาชิก.pdf'],
            ['name' => 'แบบฟอร์มคำร้องทั่วไป', 'path' => 'content/forms/แบบฟอร์มคำร้องทั่วไป.pdf'],
            ['name' => 'แบบฟอร์มคำขอรับสวัสดิการเสียชีวิต', 'path' => 'content/forms/คำรับสวัสดิการกรณีเสียชีวิต.pdf'],
            ['name' => 'แบบฟอร์มคำขอลาออกสมาชิกเสียชีวิต', 'path' => 'content/forms/แบบฟอร์มคำขอลาออกสมาชิกเสียชีวิต.pdf'],
            ['name' => 'แบบฟอร์มยินยอมหักผ่านบัญชี', 'path' => 'content/forms/แบบฟอร์มคำขอชำระผ่านการหัก.pdf'],
            ['name' => 'แบบฟอร์มคำขอลาออกสมาชิก', 'path' => 'content/forms/คำขอลาออกสมาชิก.pdf'],
            ['name' => 'ใบสมัครเข้าร่วมโครงการ', 'path' => 'content/forms/ใบสมัครเข้าร่วมโครงการ.pdf'],
            ['name' => 'Check list สินเชื่อฮาลาล', 'path' => 'content/forms/CHECK LIST.pdf'],
            ['name' => 'LY-SH-003-69 แบบคำขอไถ่ถอนจากจำนอง', 'path' => 'content/forms/LY-SH-003-69 แบบคำขอไถ่ถอนจากจำนอง.pdf'],
            ['name' => 'LY-SH-002-69 แบบคำขออนุมัติใช้หลักทรัพย์ระหว่างจำนอง', 'path' => 'content/forms/LY-SH-002-69 แบบคำขออนุมัติใช้หลักทรัพย์ระหว่างจำนอง.pdf'],
            ['name' => 'LY-SH-001-69 แบบคำขอปลอด หรือ เปลี่ยนแปลงหลักทรัพย์', 'path' => 'content/forms/LY-SH-001-69 แบบคำขอปลอด หรือ เปลี่ยนแปลงหลักทรัพย์.pdf'],
        ],
    ],

    'branches' => [
        [
            'id' => 'nuea_khlong',
            'name' => 'สาขาเหนือคลอง',
            'address' => '123/2 ม.1 ต.คลองเขม้า อ.เหนือคลอง จ.กระบี่ 81130',
            'phone' => '088-262-0995, 075-810534',
            'image' => 'content/branches/ton_thuai.jpg',
            'latitude' => 8.021063,
            'longitude' => 98.995649,
        ],
        [
            'id' => 'krabi',
            'name' => 'สาขากระบี่',
            'address' => 'เลขที่ 199/9-10 ถนนกระบี่-เขาทอง ตำบลปากน้ำ อำเภอเมือง จังหวัดกระบี่ 81000',
            'phone' => '075-652-525',
            'image' => 'content/branches/krabi.jpg',
            'latitude' => 8.063564,
            'longitude' => 98.908573,
        ],
        [
            'id' => 'koh_lanta',
            'name' => 'สาขาเกาะลันตา',
            'address' => 'เลขที่ 100 หมู่ที่ 2 ตำบลศาลาด่าน อำเภอเกาะลันตา จังหวัดกระบี่ 81150',
            'phone' => '075-667-226',
            'image' => 'content/branches/koh_lanta.jpg',
            'latitude' => 7.594943,
            'longitude' => 99.034851,
        ],
        [
            'id' => 'khlong_yang',
            'name' => 'สำนักงานใหญ่',
            'address' => 'เลขที่ 291 หมู่ที่ 1 ตำบลคลองยาง อำเภอเกาะลันตา จังหวัดกระบี่ 81120',
            'phone' => '075-652-525',
            'image' => 'content/branches/khlong_yang.jpg',
            'latitude' => 7.803235,
            'longitude' => 99.085919,
        ],
        [
            'id' => 'shell_krabi',
            'name' => 'สถานีบริการน้ำมันเชลล์',
            'address' => 'สถานีบริการน้ำมันเชลล์ จังหวัดกระบี่',
            'phone' => '075-652-525',
            'image' => 'content/branches/shell-marker.jpg',
            'latitude' => 7.811404,
            'longitude' => 99.091178,
            'markerLogo' => 'content/logos/shell-marker-logo.jpg',
            'markerKind' => 'fuel',
            'group' => 'business',
        ],
        [
            'id' => 'ao_luek',
            'name' => 'สาขาอ่าวลึก',
            'address' => 'เลขที่ 59/24 หมู่ที่ 4 ตำบลคลองหิน อำเภออ่าวลึก จังหวัดกระบี่ 81110',
            'phone' => '075-665-634',
            'image' => 'content/branches/ao_luek.jpg',
            'latitude' => 8.303262,
            'longitude' => 98.781841,
        ],
        [
            'id' => 'kanchanadit',
            'name' => 'สาขากาญจนดิษฐ์',
            'address' => 'เลขที่ 111/47 หมู่ที่ 2 ตำบลท่าทองใหม่ อำเภอกาญจนดิษฐ์ จังหวัดสุราษฎร์ธานี 84290',
            'phone' => '086-4759102',
            'image' => 'content/branches/kanchanadit.jpg',
            'latitude' => 9.148572,
            'longitude' => 99.393332,
        ],
        [
            'id' => 'huai_luek',
            'name' => 'สาขาห้วยลึก',
            'address' => 'เลขที่ 14/10 หมู่ที่ 1 ตำบลทรายขาว อำเภอคลองท่อม จังหวัดกระบี่ 81170',
            'phone' => '075-810-672',
            'image' => 'content/branches/huai_luek.jpg',
            'latitude' => 7.759844,
            'longitude' => 99.24161,
        ],
        [
            'id' => 'khlong_thom',
            'name' => 'สาขาคลองท่อม',
            'address' => 'เลขที่ 218/1-2 หมู่ที่ 2 ตำบลคลองท่อมใต้ อำเภอคลองท่อม จังหวัดกระบี่ 81120',
            'phone' => '075-702-745',
            'image' => 'content/branches/khlong_thom.jpg',
            'latitude' => 7.940006,
            'longitude' => 99.144035,
        ],
    ],

    'business_units' => [
        [
            'id' => 'sakofah_school',
            'name' => 'โรงเรียนษะกอฟะฮวิทยพัฒน์',
            'address' => 'โรงเรียนษะกอฟะฮวิทยพัฒน์',
            'phone' => '-',
            'image' => 'content/branches/sakofah-school.jpg',
            'markerLogo' => 'content/logos/sakofah-school.jpg',
            'latitude' => 8.0761628,
            'longitude' => 98.8971632,
            'group' => 'business',
            'markerKind' => 'business',
        ],
        [
            'id' => 'skf_stadium',
            'name' => 'SKF Stadium Sport Club คลองยาง',
            'address' => 'สนามฟุตบอลหญ้าเทียม SKF Stadium Sport Club คลองยาง',
            'phone' => '-',
            'image' => 'content/branches/skf-stadium.jpg',
            'markerLogo' => 'content/logos/skf-stadium.jpg',
            'latitude' => 7.8105798,
            'longitude' => 99.0902488,
            'group' => 'business',
            'markerKind' => 'business',
        ],
        [
            'id' => 'sakofah_foundation',
            'name' => 'มูลนิธิษะกอฟะฮ',
            'address' => 'มูลนิธิษะกอฟะฮ',
            'phone' => '-',
            'image' => 'content/branches/sakofah-foundation.jpg',
            'markerLogo' => 'content/logos/sakofah-foundation.jpg',
            'latitude' => 7.810533,
            'longitude' => 99.090014,
            'group' => 'business',
            'markerKind' => 'business',
        ],
        [
            'id' => 'ummah_channel',
            'name' => 'Ummah Channel / นำสื่อที่ดี สู่มวลชน',
            'address' => 'Ummah Channel / นำสื่อที่ดี สู่มวลชน',
            'phone' => '-',
            'image' => 'content/branches/ummah-channel.png',
            'markerLogo' => 'content/logos/logo-ummah-channel.png',
            'latitude' => 7.810613,
            'longitude' => 99.090014,
            'group' => 'business',
            'markerKind' => 'business',
        ],
        [
            'id' => 'southern_coffee_khlong_yang',
            'name' => 'Southern Coffee คลองยาง',
            'address' => 'Southern Coffee คลองยาง',
            'phone' => '-',
            'image' => 'content/branches/southern-coffee.png',
            'markerLogo' => 'content/logos/southern-coffee-logo.png',
            'latitude' => 7.811498,
            'longitude' => 99.091009,
            'group' => 'business',
            'markerKind' => 'business',
        ],
    ],

    'branch_order' => [
        'khlong_yang',
        'krabi',
        'ao_luek',
        'koh_lanta',
        'khlong_thom',
        'huai_luek',
        'kanchanadit',
        'nuea_khlong',
        'shell_krabi',
        'sakofah_school',
        'skf_stadium',
        'sakofah_foundation',
        'ummah_channel',
        'southern_coffee_khlong_yang',
    ],
];

